import React, { useState } from 'react';
import { Coffee, Globe } from 'lucide-react';
import RecipeGenerator from './components/RecipeGenerator';
import ChatInterface from './components/ChatInterface';
import { Language } from './types';

const App: React.FC = () => {
  const [language, setLanguage] = useState<Language>('zh');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'zh' : 'en');
  };

  const t = {
    title: language === 'en' ? 'CoffeeMaster AI' : '咖啡大师 AI',
    subtitle: language === 'en' ? 'Powered by Gemini 2.5 & Imagen 3' : '由 Gemini 2.5 & Imagen 3 驱动',
    heroTitle: language === 'en' ? 'Your Personal AI Barista' : '您的私人 AI 咖啡师',
    heroText: language === 'en' 
      ? 'Craft the perfect cup with custom recipes generated by AI, or have a conversation with our expert brewing assistant.'
      : '利用 AI 生成的定制食谱制作完美的咖啡，或与我们的专家级冲煮助手畅谈咖啡之道。',
    footer: language === 'en' ? 'CoffeeMaster AI. Brewing intelligence.' : '咖啡大师 AI。 智造醇香。'
  };

  return (
    <div className="min-h-screen bg-coffee-50 text-coffee-900 font-sans selection:bg-coffee-200">
      {/* Header */}
      <header className="bg-white border-b border-coffee-200 sticky top-0 z-10 shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-coffee-600 rounded-lg text-white">
              <Coffee size={24} />
            </div>
            <h1 className="font-serif text-xl font-bold text-coffee-800 tracking-tight">
              {t.title}
            </h1>
          </div>
          
          <div className="flex items-center gap-4">
             <button 
               onClick={toggleLanguage}
               className="flex items-center gap-2 px-3 py-1.5 rounded-full bg-coffee-50 hover:bg-coffee-100 text-coffee-700 text-sm font-medium transition-colors border border-coffee-200"
             >
               <Globe size={16} />
               <span>{language === 'en' ? '中文' : 'English'}</span>
             </button>
            <div className="text-sm text-coffee-600 font-medium hidden sm:block">
              {t.subtitle}
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="text-center mb-12 max-w-2xl mx-auto">
          <h2 className="text-4xl font-serif font-bold text-coffee-900 mb-4">
            {t.heroTitle}
          </h2>
          <p className="text-coffee-600 text-lg leading-relaxed">
            {t.heroText}
          </p>
        </div>

        <div className="grid lg:grid-cols-2 gap-8 items-start">
          {/* Left Column: Recipe Generator */}
          <div className="space-y-6">
            <RecipeGenerator language={language} />
          </div>

          {/* Right Column: Chat Interface */}
          <div className="sticky top-24">
            <ChatInterface language={language} />
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-coffee-900 text-coffee-100 py-8 mt-12">
        <div className="max-w-7xl mx-auto px-4 text-center text-sm opacity-80">
          <p>&copy; {new Date().getFullYear()} {t.footer}</p>
        </div>
      </footer>
    </div>
  );
};

export default App;
